#!/bin/bash

clear
echo -e "************************************************"
echo -e "#      SCRIPT AUTO INSTALL VPN BY gandring      #"
echo -e "*************************************************"
echo -e "# Debian 9 & Debian 10 64 bit                   #"
echo -e "# Ubuntu 18.04 & Ubuntu 20.04 64 bit            #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Luxury Edition By gandring                    #"
echo -e "*************************************************"
echo -e "#         PUJI SYUKUR DAN TERIMAKASIH           #"
echo -e "*************************************************"
echo -e "# Allah SWT                                     #"
echo -e "# Muhammad SAW                                  #"
echo -e "# Keluarga Besarku                              #"
echo -e "# github                                        #"
echo -e "# geovpn                                        #"
echo -e "# senovpn                                       #"
echo -e "#            SOLO THE SPIRIT OF JAVA            #"
echo -e "================================================="
